global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using SQLite;
global using Microsoft.Extensions.Logging;
global using SalaryCounter.Models;
global using SalaryCounter.Views;
